"""Add user_id

Revision ID: e0f190bed51f
Revises: e1f656bb9d71
Create Date: 2026-08-29 17:43:31.050449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f190bed51f'
down_revision: Union[str, Sequence[str], None] = 'e1f656bb9d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_sessions', sa.Column('user_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_research_sessions_user_id'), 'research_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_sessions_user_id'), table_name='research_sessions')
    op.drop_column('research_sessions', 'user_id')
    # ### end Alembic commands ###
